### ISSUE TITLE
Race conditions in the original library

### ISSUE THREAD

**Issue by lzap** [keegancsmith/rpc#6]
Hey, thanks for the effort. There were some concerns raised by Rob when he proposed to freeze the stdlib package and when I digged into the problems, it looks like there are some "hard to solve" problems.

* https://github.com/golang/go/issues/16844
* https://github.com/golang/go/issues/5792
* https://github.com/golang/go/issues/17239

I am wondering if these are solved in this fork, specifically the last bug (race condition when closing) which was mentioned as "really hard to solve". Can contexts with deadline/timeout be used for this, my idea is:

* Set a short timeout.
* During graceful shutdown, wait the timeout + extra second to let all inflight calls to be cancelled.
* Close the pipe and terminate the program.

I have built a small RPC over pipe solution (https://github.com/lzap/cborpc) where I use the net/rpc (with CBOR custom codec) over pipe to subproces (https://github.com/lzap/cborpc/blob/main/cmd/command.go) so that's why I am asking. I really like ability to use contexts anyway, so I will very likely migrate to your library.

Thanks for any hints or pointers, feel free to close the issue, this is more of a discussion but I was not sure where to go.

**Comment by lzap** [comment]
So after reading the project history, I understand now. Good job splitting everything into well documented commits! I guess my (wild) usecase (calling Python from Go as a subprocess) is not great fit for Go Contexts, more than that there is a special call `_goRPC_.Cancel` that needs to be implemented serverside.

I guess for my PIPE transport, I will simply do just client side cancellation and wait group for in-flight requests so I can shutdown and close the pipe gracefully.

Sorry for the noise.

**Comment by keegancsmith** [comment]
Thanks for taking a look and linking to upstream bugs. I'm happy 
to look into fixing those bugs, since we use this in production at 
my day job.

FYI a popular choice for what you are doing is something like 
jsonrpc2.  You should find lots of libraries on both the server 
and client side in both python and go.

**Comment by lzap** [comment]
I guess there is no need for any sort of investigation, since your code is apparently serving your prod well. I was just generally curious but now that I see it's not applicable to my use case, feel free to forget about this :-)

I am pretty sad that net/rpc is gone from the stdlib, it's so lightweight and it just feels right for Go-to-Go RPC. I just created a CLI-SERVICE prototype the other day and it was so smooth, the only missing bit was the context. I am pretty sure I will be asked to use REST for the final version so... :-D

**Comment by keegancsmith** [comment]
So I was nerd sniped by this since it made me realise why we see some weird behaviour around shutdowns. I'm gonna implement a `Shutdown` function that will stop reading but wait for all inflight requests to return. This won't inform the client that it has stopped accepting unfortunetly. Alternatively I'm considering just a `Close` which will close hard shutdown. Will see once I've written code and tested to see which one makes more sense (or both).

These can be used with `net.Server.RegisterOnShutdown` (or in your case something you will have to roll yourself).

FYI I looked into the race condition, and it was solved in the go stdlib. They added a waitgroup for inflight requests, and then only call close on the codec once they all return. This library already has that code.
